#-- question 7 
SELECT C.CARTON_ID, (C.LEN*C.WIDTH*C.HEIGHT) as VOL
FROM ORDERS.CARTON C
	WHERE (C.LEN*C.WIDTH*C.HEIGHT) >= (
			SELECT
			SUM(P.LEN*P.WIDTH*P.HEIGHT*PRODUCT_QUANTITY) AS VOL
			FROM ORDERS.ORDER_HEADER OH
			INNER JOIN ORDERS.ORDER_ITEMS OI ON OH.ORDER_ID = OI.ORDER_ID
			INNER JOIN ORDERS.PRODUCT P ON OI.PRODUCT_ID =
			P.PRODUCT_ID
			WHERE OH.ORDER_ID =10006 
			)
ORDER BY (C.LEN*C.WIDTH*C.HEIGHT) ASC
LIMIT 1 ;

#-- question 8 
SELECT C.CUSTOMER_ID, C.CUSTOMER_FULLNAME, OUT_QRY.PRODUCT_QUANTITY, H.ORDER_ID
FROM
(
	SELECT ORDER_ID, PRODUCT_QUANTITY FROM ORDERS.ORDER_ITEMS
	GROUP BY ORDER_ID
	HAVING SUM(PRODUCT_QUANTITY) > 10
) OUT_QRY
		INNER JOIN ORDERS.ORDER_HEADER H ON OUT_QRY.ORDER_ID = H.ORDER_ID AND H.ORDER_STATUS = 'SHIPPED'
		INNER JOIN
			(
			SELECT DISTINCT CUSTOMER_ID,
			CONCAT(CUSTOMER_FNAME,' ',CUSTOMER_LNAME) AS CUSTOMER_FULLNAME FROM
			ORDERS.ONLINE_CUSTOMER
			) C ON H.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY C.CUSTOMER_ID;

#-- question 9 

SELECT OI.ORDER_ID, OC.CUSTOMER_ID, CONCAT(OC.CUSTOMER_FNAME,' ',OC.CUSTOMER_LNAME) AS CUSTOMER_NAME, OI.TOTAL_QUANTITY
FROM ORDERS.ORDER_HEADER OH
	INNER JOIN
			(
				SELECT ORDER_ID,
				SUM(PRODUCT_QUANTITY) AS TOTAL_QUANTITY FROM ORDERS.ORDER_ITEMS
				GROUP BY ORDER_ID
				HAVING
				ORDER_ID > 10060
			) OI 
				ON OH.ORDER_ID = OI.ORDER_ID AND OH.ORDER_STATUS = 'SHIPPED'
INNER JOIN ORDERS.ONLINE_CUSTOMER OC ON OH.CUSTOMER_ID = OC.CUSTOMER_ID;

#-- question 10 

SELECT OUT_QRY.PRODUCT_CLASS_DESC, SUM(OUT_QRY.PRODUCT_QUANTITY) PRODUCT_QUANTITY, SUM(OUT_QRY.TOTAL_VALUE) TOTAL_VALUE, OUT_QRY.PRODUCT_CLASS_CODE
	FROM
		(
		SELECT PC.PRODUCT_CLASS_DESC, OI.PRODUCT_QUANTITY, (OI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) TOTAL_VALUE, PC.PRODUCT_CLASS_CODE
		FROM ORDERS.ORDER_ITEMS OI
			INNER JOIN ORDERS.ORDER_HEADER OH ON OH.ORDER_ID = OI.ORDER_ID AND OH.ORDER_STATUS = 'SHIPPED'
			INNER JOIN ORDERS.ONLINE_CUSTOMER OC ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
			INNER JOIN ORDERS.ADDRESS A ON OC.ADDRESS_ID = A.ADDRESS_ID AND A.COUNTRY NOT IN ('India','USA') 
			LEFT JOIN ORDERS.PRODUCT P ON OI.PRODUCT_ID = P.PRODUCT_ID
			LEFT JOIN ORDERS.PRODUCT_CLASS PC ON P.PRODUCT_CLASS_CODE = PC.PRODUCT_CLASS_CODE
		) OUT_QRY
GROUP BY OUT_QRY.PRODUCT_CLASS_CODE, OUT_QRY.PRODUCT_CLASS_DESC
ORDER BY SUM(OUT_QRY.PRODUCT_QUANTITY) DESC
LIMIT 1;
